app = "facetime-v3"
primary_region = "den"

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "rolling"

[[services]]
internal_port = 8081
protocol = "udp"

[[services.ports]]
port = "8081"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = "8080"
