app = 'facetime-v3'
primary_region = 'den'

[build]
dockerfile = 'Dockerfile'

[deploy]
strategy = 'rolling'

[[services]]
protocol = 'udp'
internal_port = 8081

[[services.ports]]
port = 8081

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 8080

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
